export const metadata = {
  title: "Ingresando Nuevo Producto",
  description: "Generated by create next app",
};


function layout({children}) {
  return (
    <div>
      {children}
    </div>
  )
}

export default layout
